Hil driver
BUEC528-HIL-QUADS/quads pull request #27
Opened 2017-03-29 03:46 UTC by Hugh472

I know that merging this manually will take some doing, but I just wanted to throw this up here.  I have several questions for Dan regarding the update methods.

2017-03-29 13:24 UTC, SahilTikale commented
Make a mock driver with the all the "mocking" all the functionality that a HIL driver is supposed to have. 
This way you can make sure that the interface class you ensures the interfaces you require for any network isolation driver like HIL. Also having the mock driver makes it easy to test the functionality on your own system.

2017-03-29 13:27 UTC, SahilTikale commented
what is the difference between `hilDriver` and `hil_driver`. Why do have two drivers doing almost similar things ?

2017-03-29 13:29 UTC, SahilTikale commented
Once you write the mock driver, try to write some unit tests showing how the driver is used by QUADS to call HIL and HIL like systems.

2017-03-29 14:28 UTC, Hugh472 commented
Sahil, this driver is not quite finished, as you point out, and hil_driver is supposed to be deleted in favor of an updated HilDriver(just for naming convention purposes, I've fixed this in my local files).  Isaac and I have discussed some necessary further changes, and I will definitely take your advice about writing a few unit tests.

2017-04-07 18:58 UTC, portante requested changes

2017-04-07 18:58 UTC, portante commented on lib/libquads.py
> +        set_hardware_service(HilDriver()) #temporary hardcode to HIL
Can we remove this replaced-hardcoded driver and do this from the configuration file?

2017-04-07 18:58 UTC, portante commented on lib/test_mock.py
> +from hardware_services.hardware_drivers.hil_driver import HilDriver
Why are we doing this in the test environment?  Wouldn't we always want to use Mock here?

2017-04-07 18:58 UTC, portante commented on lib/test_mock.py
> +#cls.update_cloud()
This seems bad ...

2017-04-10 13:21 UTC, portante commented
@Hugh472, how does this PR reconcile with #30?

2017-04-21 15:59 UTC, saacg commented
closing as it has been superseded by more recent work.

2017-04-21 15:59 UTC, closed without merging