Cleanup
BUEC528-HIL-QUADS/quads pull request #29
Opened 2017-04-05 00:49 UTC by vsemp

Cleaning up our master.

2017-04-05 01:00 UTC, saacg commented on lib/libquads.py
> -            print r.text
Can we keep this function? We still use it.

2017-04-05 01:05 UTC, vsemp commented on lib/libquads.py
> -            print r.text
Sure. I will rewrite it.

2017-04-06 15:47 UTC, saacg requested changes

2017-04-06 15:47 UTC, saacg commented on lib/hardware_service.py
> +class HardwareService(object):
@vsemp as we have discussed,there is a lot of code already implemented for the hardware_service class and its concrete subclasses in the decouple-juniper branch. Can you branch off that, and then add your changes there, building on what has already been done? Then we can reuse the code we have already implemented and tested, and not have to completely redesign everything.

2017-04-06 15:53 UTC, saacg requested changes

2017-04-06 15:53 UTC, saacg commented on hil_starter.sh
> +start_hil_server(){
@vsemp this script seems to require the existence of HIL in some directory on the user's local machine. I think in previous discussions it was decided that we should keep this out of QUADS? Perhaps you could put this in HIL instead? Then you could still use this script to automate running the servers, but would not be adding any HIL dependencies to QUADS.

2017-04-06 15:57 UTC, vsemp commented on hil_starter.sh
> +start_hil_server(){
It's a separate file and you can always delete it. If I move this script elsewhere it, probably, won't be used because other people won't see it.

2017-04-06 15:59 UTC, vsemp commented on lib/hardware_service.py
> +class HardwareService(object):
All my files are separate files. You can always delete them in no time.

The code in bin and libquads.py is the Red-Hat code. I think we should use it as a baseline.

2017-04-06 16:08 UTC, saacg requested changes

2017-04-06 16:08 UTC, saacg commented on lib/hil/hil.py
> +
@vsemp this file provides many useful wrapper functions to abstract the rest calls to the HIL api. However, i'm not sure we want to add another cli to QUADS, let alone one that is specific to HIL. Maybe we could get rid of the command line parsing, and add these as private methods when we implement the concrete HIL inventory class?

2017-04-06 16:10 UTC, vsemp commented on lib/hil/hil.py
> +
hil folder is reserved for HIL specific driver

2017-04-06 16:20 UTC, saacg commented on hil_starter.sh
> +start_hil_server(){
@vsemp why would we merge code with the intention of deleting it?

2017-04-06 16:20 UTC, saacg commented on lib/hil/hil.py
> +
@vsemp these are HIL specific functions

2017-04-07 19:01 UTC, portante requested changes
Seems like all the files were changed to add execute privilege, 644 -> 755.

Do we have to do that?

2017-04-07 21:00 UTC, closed without merging