redesign
BUEC528-HIL-QUADS/quads pull request #37
Opened 2017-04-08 23:46 UTC by vsemp

Just for mentors to review it.

2017-04-09 16:19 UTC, saacg commented on lib/hil/hil.py
> +   main()
please see conversation here: https://github.com/BUEC528-HIL-QUADS/quads/pull/35#discussion_r110508083

2017-04-09 16:25 UTC, saacg commented on lib/hil/hil.py
> +   main()
This file provides many useful wrapper functions to abstract the rest calls to the HIL api. However, i'm not sure we want to add another cli to QUADS, let alone one that is specific to HIL. Maybe we could get rid of the command line parsing, and add these as private methods when we implement the concrete HIL inventory class?

2017-04-09 16:27 UTC, saacg commented on lib/hil/hil_starter.sh
> +sleep 1
This script seems to require the existence of HIL in some directory on the user's local machine. I think in previous discussions it was decided that we should keep this out of QUADS? Perhaps if we want to use this we could put this in HIL instead? Then you could still use this script to automate running the servers, but would not be adding any HIL dependencies to QUADS.

2017-04-10 13:08 UTC, portante requested changes
It is important when writing new code and proposing changes to a body of work to properly motivate why you are making the changes.  The changes themselves are not the motivating factor.

Having a write-up in the commit message with they why, how it is of benefit to the community of users of this code base, and how you are going to use them is pretty important.

2017-04-10 13:08 UTC, portante commented on lib/hil/hil.yml
> +url: http://127.0.0.1:5000
What is this file for exactly?  It has one line, and no comments.

2017-04-10 18:17 UTC, vsemp commented on lib/hil/hil.yml
> +url: http://127.0.0.1:5000
I'm confused. I thought commit messages are very short.

Should I put this explanation into PR comment?

2017-04-21 16:02 UTC, saacg commented
closing as it has been replaced with newer changes.

2017-04-21 16:02 UTC, closed without merging